name: Deploy Node.js App to Server - Peekhosting.com
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    #   # Navigate to backend-portal directory, install dependencies, and build
    #   - name: Install dependencies for Node.js App
    #     working-directory: ./backend-portal
    #     run: |
    #       npm install

      # Upload backend-portal to the server via FTP
      - name: Upload Portal backend Files to Server via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./backend-portal" # Directory to upload (Node.js app files)
          remote_dir: "/" # Target directory on the server (outside public_html if possible)
          ftp_ssl_allow: "true"      # Enable SSL if server requires it
          ftp_use_feat: "true"       # Enable FTP FEAT if server requires it
